version: 2
jobs:
  publish:
    docker:
    - image: cimg/node:lts
    steps:
    - checkout
    - run:
        command: |
          sudo apt-get update && sudo apt-get install -y software-properties-common python3-requests
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt-get update && sudo apt-get install -y gh
          PCC_VERSION="$(echo "$CIRCLE_TAG" | sed 's/^v//')"
          export PCC_VERSION
          ./make_scripts/make_UXP.py
          npm set prefix=/home/circleci/npm && echo 'export PATH=$HOME/circleci/npm/bin:$PATH' >> /home/circleci/.bashrc && npm install web-ext chrome-webstore-upload-cli && ./make_scripts/make_webext.py firefox && ./make_scripts/make_webext.py chromium || true
          ./make_scripts/make_checksum.py
          gh release create "$CIRCLE_TAG" ./artifacts/* --notes "WIP"
    environment:
      TEST_MODE: "false"
workflows:
  version: 2
  workflow:
    jobs:
      - publish:
          filters:
            tags:
              ignore: /legacy.*/
            branches:
              ignore: /.*/
          context: org-global
