version: 2
jobs:
  publish:
    docker:
    - image: circleci/golang:latest-node
    steps:
    - checkout
    - run: go get github.com/tcnksm/ghr
    - run: npm set prefix=/home/circleci/npm && echo 'export PATH=$HOME/circleci/npm/bin:$PATH' >> /home/circleci/.bashrc && npm install web-ext-submit && ./make_scripts/make_chromium.sh && ./make_scripts/make_firefox.sh
    - run: ghr -t ${GH_TOKEN} -u PolishFiltersTeam -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./src/web-ext-artifacts
workflows:
  version: 2
  workflow:
    jobs:
      - publish:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          context: org-global
