name: Błędy w dodatku 🐞
description: Bugs 🐞, mistakes🤦‍♂️, no-no 🥺 (in Add-on)
labels: błąd

body:
  - type: markdown
    attributes:
      value: |
        Dziękujemy za zgłoszenie błędu do repozytorium Polskiej Zgody Ciasteczkowej!
        Thanks for reporting bug to Polish Cookie Consent repository!
  - type: input
    id: adblocker
    attributes:
      label: Bloker (Blocker)
      placeholder: uBlock Origin 1.35.2
    validations:
      required: true
  - type: input
    id: PCC
    attributes:
      label: Wersja dodatku PZC (Version of PCC Add-on)
      placeholder: 1.47.1
    validations:
      required: true
  - type: textarea
    id: specificURL
    attributes:
      label: Link bezpośredni, na którym występuje problem
      description: A specific URL where the problem occurs
      placeholder: https://www.biedronka.pl/nowagazetka
      render: markdown
  - type: textarea
    id: bugDesc
    attributes:
      label: Opis błędu
      description: A bug description
      placeholder: |
        Pole na opis błedu.
        Area to describe bug.
    validations:
      required: true
  - type: textarea
    id: otherInfo
    attributes:
      label: Dodatkowe informacje mogące mieć znaczenie
      description: Additional information that may be relevant
      placeholder: |
        Zrzuty ekranu, twoja metoda rozwiązania problemu i inne ważne informacje.
        Screenshots, your method of solving the problem and other important information.
